import { z } from 'zod/v4';
import type { Env } from '../types';
export const ROOM_SLUGS = ['announcements','introductions','general','questions','resources','chat'] as const;
export const communityInputSchema = z.object({name:z.string().trim().min(1).max(80),purpose:z.string().trim().min(1).max(300),preset:z.enum(['general','club','creator','project','support']),language:z.enum(['en','he'])}).strict();
const article = z.object({title:z.string().trim().min(1).max(200),content:z.string().trim().min(1).max(6000)}).strict();
export const communityDraftSchema=communityInputSchema.extend({version:z.literal(1),homepageCopy:z.string().trim().min(1).max(2000),rules:z.string().trim().min(1).max(10000),welcome:article,joiningGuide:article,rooms:z.array(z.object({slug:z.enum(ROOM_SLUGS),name:z.string().trim().min(1).max(100),description:z.string().trim().min(1).max(500)}).strict()).length(6),discussions:z.array(article.extend({roomSlug:z.enum(['general','questions','resources'])})).length(3)}).strict().refine(d=>d.rooms.every((r,i)=>r.slug===ROOM_SLUGS[i]),'Rooms must follow the application preset');
export type CommunityDraft=z.infer<typeof communityDraftSchema>;
export type CommunityInput=z.infer<typeof communityInputSchema>;
const contexts={general:['community','קהילה'],club:['local group','קבוצה מקומית'],creator:['creator community','קהילת יוצרים'],project:['project team','צוות הפרויקט'],support:['support community','קהילת תמיכה']} as const;
const profiles={
 general:{en:['Announcements','Introductions','General discussion','Questions','Resources','Community chat','What would you like to find here?','Share one idea or a topic for discussion.'],he:['הודעות','היכרות','דיון כללי','שאלות','משאבים','צ׳אט קהילתי','מה תרצו למצוא כאן?','שתפו רעיון אחד או נושא לשיחה.']},
 club:{en:['Group notices','Meet your neighbors','Local conversations','Local questions','Local guides','Group chat','What should our next gathering include?','Suggest an accessible activity, meeting place or topic. Avoid publishing private addresses.'],he:['הודעות הקבוצה','נכיר את השכנים','שיחות מקומיות','שאלות מקומיות','מדריכים מקומיים','צ׳אט הקבוצה','מה כדאי לכלול במפגש הבא?','הציעו פעילות נגישה, מקום מפגש או נושא. הימנעו מפרסום כתובות פרטיות.']},
 creator:{en:['Creator updates','Meet the community','Creative conversations','Ask the creator','Creative resources','Community lounge','What would you like to create or explore?','Suggest a creative theme, format or question, and share what interests you.'],he:['עדכוני היוצר','נכיר את הקהילה','שיחות יצירתיות','שאלות ליוצר','משאבים ליצירה','סלון הקהילה','מה תרצו ליצור או לחקור?','הציעו נושא יצירתי, פורמט או שאלה ושתפו מה מעניין אתכם.']},
 project:{en:['Project updates','Meet the team','Project ideas','Project questions','Project documentation','Team chat','What should we work on first?','Describe a useful goal, who it helps and a small first step.'],he:['עדכוני הפרויקט','נכיר את הצוות','רעיונות לפרויקט','שאלות על הפרויקט','תיעוד הפרויקט','צ׳אט הצוות','במה כדאי להתחיל לעבוד?','תארו יעד מועיל, למי הוא עוזר וצעד ראשון קטן.']},
 support:{en:['Community notices','Introduce yourself','Share and connect','Ask for support','Helpful resources','Support chat','What helps you feel welcome and supported?','Share a boundary, an encouragement or a useful practice if comfortable. Personal details are optional.'],he:['הודעות הקהילה','הציגו את עצמכם','שיתוף וקשר','בקשת תמיכה','משאבים מועילים','צ׳אט תמיכה','מה עוזר לכם להרגיש רצויים ונתמכים?','שתפו גבול, עידוד או הרגל מועיל אם נוח לכם. אין צורך לחשוף פרטים אישיים.']}
} as const;
export function makeCommunityDraft(input:CommunityInput):CommunityDraft {
 const i=communityInputSchema.parse(input),he=i.language==='he',context=contexts[i.preset][he?1:0];
 const profile=profiles[i.preset][i.language],names=profile.slice(0,6);
 const descriptions=he?[`עדכונים רשמיים של ${context}.`,'ספרו קצת על עצמכם ובמה תרצו להשתתף.',`שיחות ורעיונות של ${context}.`,'בקשו עזרה ושתפו תשובות מועילות.','שתפו מדריכים, קישורים וכלים שימושיים.','שיחות בזמן אמת עם חברי הקהילה.']:[`Official updates for this ${context}.`,'Introduce yourself and what you hope to contribute.',`Conversations and ideas for this ${context}.`,'Ask for help and share useful answers.','Share helpful guides, links and tools.','Talk with fellow members in real time.'];
 return communityDraftSchema.parse({...i,version:1,homepageCopy:he?`ברוכים הבאים אל ${i.name}. ${i.purpose}\nמקום לשאול, לשתף ולהתחבר.`:`Welcome to ${i.name}. ${i.purpose}\nA place to ask, share and connect.`,rules:he?'נהגו בכבוד ובסבלנות. שמרו על פרטיותכם ועל פרטיות אחרים. אין הטרדה, ספאם או פרסום מידע אישי ללא הסכמה. ציינו מקורות והקשיבו להנחיות הצוות.':'Be respectful and patient. Protect your privacy and the privacy of others. No harassment, spam or sharing personal information without consent. Credit sources and follow staff guidance.',welcome:{title:he?'ברוכים הבאים!':'Welcome!',content:he?`ברוכים הבאים אל ${i.name}! ${i.purpose}\nקראו את הכללים, הציגו את עצמכם ופתחו שיחה כשאתם מוכנים.`:`Welcome to ${i.name}! ${i.purpose}\nRead the rules, introduce yourself, and start a conversation when you are ready.`},joiningGuide:{title:he?'איך מצטרפים ומשתתפים':'How to join and take part',content:he?'אפשר לקרוא את הדיונים ללא חשבון. כדי להשתתף, בקשו הזמנה מבעלי הקהילה. לאחר ההצטרפות, הציגו את עצמכם ושאלו שאלה או שתפו רעיון. הודעות רשמיות מתפרסמות על ידי הצוות.':'You can read discussions without an account. To participate, ask the community owner for an invitation. After joining, introduce yourself and ask a question or share an idea. Official announcements are posted by staff.'},rooms:ROOM_SLUGS.map((slug,n)=>({slug,name:names[n],description:descriptions[n]})),discussions:he?[{roomSlug:'general',title:profile[6],content:`${i.name}: ${profile[7]}`},{roomSlug:'questions',title:'יש לכם שאלה ראשונה?',content:'שאלו שאלה, הוסיפו את ההקשר הרלוונטי וציינו מה כבר ניסיתם. אין צורך לשתף פרטים אישיים.'},{roomSlug:'resources',title:'איזה משאב כדאי להכיר?',content:'שתפו מדריך או כלי שימושי, והסבירו בקצרה למי הוא יכול לעזור.'}]:[{roomSlug:'general',title:profile[6],content:`${i.name}: ${profile[7]}`},{roomSlug:'questions',title:'What is your first question?',content:'Ask a question, add useful context and explain what you have tried. Avoid sharing personal information.'},{roomSlug:'resources',title:'Which resource should others know about?',content:'Share a helpful guide or tool and briefly explain who it can help.'}]});
}
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderCommunityPreview(input:CommunityDraft):string {
 const d=communityDraftSchema.parse(input),he=d.language==='he';
 return `<section class="community-preview" lang="${d.language}" dir="${he?'rtl':'ltr'}"><h1>${esc(d.name)}</h1><p style="white-space:pre-wrap">${esc(d.homepageCopy)}</p><div>${d.rooms.map(r=>`<article class="card"><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p></article>`).join('')}</div><article class="card"><h2>📌 ${esc(d.welcome.title)}</h2><p style="white-space:pre-wrap">${esc(d.welcome.content)}</p></article><article class="card"><h2>${esc(d.joiningGuide.title)}</h2><p>${esc(d.joiningGuide.content)}</p></article>${d.discussions.map(t=>`<article class="card"><h3>${esc(t.title)}</h3><p>${esc(t.content)}</p></article>`).join('')}<article class="card"><h2>${he?'כללי הקהילה':'Community rules'}</h2><p>${esc(d.rules)}</p></article></section>`;
}
/** Include these statements in the same D1 batch as owner creation and the setup lock. */
export function draftStatements(env:Pick<Env,'DB'>,input:CommunityDraft,ownerId:number):D1PreparedStatement[] {
 const d=communityDraftSchema.parse(input);
 const statements=d.rooms.map((r,n)=>env.DB.prepare('INSERT OR IGNORE INTO rooms(name,slug,description,kind,min_read,min_post,sort_order,is_page) VALUES(?,?,?,?,?,?,?,?)').bind(r.name,r.slug,r.description,r.slug==='chat'?'chat':r.slug==='announcements'?'news':r.slug==='questions'?'questions':'forum','anon',r.slug==='announcements'?'mod':'member',(n+1)*10,Number(r.slug==='chat')));
 const settings={branding_name:d.name,branding_description:d.purpose,branding_homepage_copy:d.homepageCopy,branding_rules:d.rules,branding_default_locale:d.language,signups_open:'0',bot_enabled:'0',seeded:'true'};
 for(const [key,value] of Object.entries(settings)) statements.push(env.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,value));
 return [...statements,...draftContentStatements(env,d,ownerId)];
}
export function draftContentStatements(env:Pick<Env,'DB'>,input:CommunityDraft,ownerId:number):D1PreparedStatement[] {
 const d=communityDraftSchema.parse(input);
 return [{...d.welcome,roomSlug:'announcements',pinned:1},{...d.joiningGuide,roomSlug:'introductions',pinned:1},...d.discussions.map(t=>({...t,pinned:0}))].map(t=>env.DB.prepare("INSERT INTO topics(room_id,user_id,title,content,status,is_pinned,short_id) SELECT id,?,?,?,'approved',?,? FROM rooms WHERE slug=?").bind(ownerId,t.title,t.content,t.pinned,crypto.randomUUID().replaceAll('-','').slice(0,12),t.roomSlug));
}
