import { z } from 'zod';
import type { Env } from '../types';
import { authorize, auditStatement, type AdminActor, type Scope } from '../mcp/auth';
import { prepareDeletion, confirmDeletion } from '../mcp/deletion';
import { loadBranding, saveBranding } from './branding';
import { sendBanEmail } from '../email';
import { notifyMentionsAndFollowers } from '../api/posts';

const id = z.number().int().positive().max(2147483647);
const text = z.string().trim().min(1).max(20000);
const note = z.string().trim().max(2000);
const pagination = { limit: z.number().int().min(1).max(100).default(25), offset: z.number().int().min(0).max(100000).default(0) };
type Operation = { description: string; scope: Scope; schema: z.ZodObject<any>; run: (env: Env, actor: AdminActor, input: any) => Promise<unknown> };
async function rows(env: Env, sql: string, values: (string | number | null)[] = []) { return (await env.DB.prepare(sql).bind(...values).all()).results; }
async function mutate(env: Env, actor: AdminActor, action: string, target: string, sql: string, values: (string | number | null)[]) {
 const result = await env.DB.batch([env.DB.prepare(sql).bind(...values), auditStatement(env, actor, action, target),env.DB.prepare('INSERT INTO audit_logs(user_id,action,details) VALUES (?,?,?)').bind(actor.id,action,target)]);
 return { changed: result[0]?.meta.changes ?? 0 };
}
const targetType = z.enum(['user','room','topic','post','badge']);
export const adminOperations: Record<string, Operation> = {
 get_branding: { description:'Read community branding.',scope:'read',schema:z.object({}).strict(),run:e=>loadBranding(e) },
 update_branding: { description:'Update community branding using the same validation as the admin panel.',scope:'configuration',schema:z.object({name:z.string().trim().min(1).max(100),description:note,logo_url:z.string().max(2000),accent_color:z.string().regex(/^#[a-fA-F0-9]{6}$/),homepage_copy:z.string().max(10000),rules:z.string().max(20000),contact_email:z.string().max(254),default_locale:z.enum(['en','he']).optional()}).strict(),run:async(e,a,i)=>{await saveBranding(e,i);await auditStatement(e,a,'update_branding','community').run();return loadBranding(e);} },
 community_stats: { description: 'Community totals without private message content.', scope:'read', schema:z.object({}).strict(), run:async env => env.DB.prepare('SELECT (SELECT count(*) FROM users) members,(SELECT count(*) FROM rooms) rooms,(SELECT count(*) FROM topics) topics,(SELECT count(*) FROM posts) replies').first() },
 list_rooms: { description:'List community spaces and permissions.',scope:'read',schema:z.object(pagination).strict(),run:(e,_,i)=>rows(e,'SELECT * FROM rooms ORDER BY sort_order,id LIMIT ? OFFSET ?',[i.limit,i.offset]) },
 create_room: { description:'Create a forum or chat space.',scope:'configuration',schema:z.object({name:z.string().trim().min(1).max(100),slug:z.string().regex(/^[a-z0-9-]{2,32}$/),description:note.default(''),icon:z.string().max(20).default(''),kind:z.enum(['forum','blog','news','questions','chat']).default('forum'),min_read:z.enum(['anon','member','full','mod']).default('anon'),min_post:z.enum(['anon','member','full','mod']).default('member'),sort_order:z.number().int().min(-100000).max(100000).default(0),locked:z.boolean().default(false),page:z.boolean().default(false),exclusive:z.boolean().default(false)}).strict(),run:(e,a,i)=>mutate(e,a,'create_room',i.slug,'INSERT INTO rooms(name,slug,description,icon,kind,min_read,min_post,sort_order,is_locked,is_page,is_exclusive) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[i.name,i.slug,i.description,i.icon,i.kind,i.min_read,i.min_post,i.sort_order,Number(i.locked),Number(i.page),Number(i.exclusive)]) },
 update_room: { description:'Change space visibility, posting access and lock status.',scope:'configuration',schema:z.object({id,name:z.string().trim().min(1).max(100),description:note,min_read:z.enum(['anon','member','full','mod']),min_post:z.enum(['member','full','mod']),locked:z.boolean(),exclusive:z.boolean()}).strict(),run:(e,a,i)=>mutate(e,a,'update_room',`room:${i.id}`,'UPDATE rooms SET name=?,description=?,min_read=?,min_post=?,is_locked=?,is_exclusive=? WHERE id=?',[i.name,i.description,i.min_read,i.min_post,Number(i.locked),Number(i.exclusive),i.id]) },
 set_room_permission: { description:'Grant, block or remove a member override for one room.',scope:'configuration',schema:z.object({room_id:id,user_id:id,access:z.enum(['blocked','read','full','remove'])}).strict(),run:(e,a,i)=>i.access==='remove'?mutate(e,a,'room_permission',`room:${i.room_id}/user:${i.user_id}`,'DELETE FROM room_permissions WHERE room_id=? AND user_id=?',[i.room_id,i.user_id]):mutate(e,a,'room_permission',`room:${i.room_id}/user:${i.user_id}`,'INSERT INTO room_permissions(room_id,user_id,access_type) VALUES (?,?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET access_type=excluded.access_type',[i.room_id,i.user_id,i.access]) },
 list_members: { description:'List member names, roles and ban status. Does not expose credentials or private messages.',scope:'read',schema:z.object(pagination).strict(),run:(e,_,i)=>rows(e,'SELECT id,display_name,access_level,is_banned,created_at FROM users ORDER BY id LIMIT ? OFFSET ?',[i.limit,i.offset]) },
 set_member_access: { description:'Change member role, preserving at least one active administrator.',scope:'members',schema:z.object({id,access:z.enum(['member','full','mod','admin'])}).strict(),run:(e,a,i)=>mutate(e,a,'member_access',`user:${i.id}`,"UPDATE users SET access_level=? WHERE id=? AND (access_level!='admin' OR is_banned=1 OR ?='admin' OR (SELECT count(*) FROM users WHERE access_level='admin' AND is_banned=0)>1)",[i.access,i.id,i.access]) },
 set_member_ban: { description:'Ban or unban a member, preserving at least one active administrator and revoking banned member sessions.',scope:'members',schema:z.object({id,banned:z.boolean(),reason:note.default('')}).strict(),run:async(e,a,i)=>{
 const result=await e.DB.batch([e.DB.prepare("UPDATE users SET is_banned=? WHERE id=? AND (access_level!='admin' OR ?=0 OR is_banned=1 OR (SELECT count(*) FROM users WHERE access_level='admin' AND is_banned=0)>1)").bind(Number(i.banned),i.id,Number(i.banned)),e.DB.prepare('DELETE FROM sessions WHERE user_id=? AND EXISTS(SELECT 1 FROM users WHERE id=? AND is_banned=1)').bind(i.id,i.id),auditStatement(e,a,'member_ban',`user:${i.id}`),e.DB.prepare("INSERT INTO mod_logs(mod_id,action,target_type,target_id,details) SELECT ?,?,'user',id,? FROM users WHERE id=? AND is_banned=?").bind(a.id,i.banned?'ban_user':'unban_user',i.reason,i.id,Number(i.banned)),e.DB.prepare('INSERT INTO audit_logs(user_id,action,details) VALUES (?,?,?)').bind(a.id,i.banned?'ban_user':'unban_user',`user=${i.id}`)]);
 const changed=result[0]?.meta.changes??0;
 if(changed&&i.banned&&i.reason) {const user=await e.DB.prepare('SELECT email FROM users WHERE id=?').bind(i.id).first<{email:string|null}>();if(user?.email)try{await sendBanEmail(e,user.email,i.reason);}catch{/* optional email delivery must not undo moderation */}}
 return {changed}; } },
 list_badges: { description:'List generic community badges.',scope:'read',schema:z.object(pagination).strict(),run:(e,_,i)=>rows(e,'SELECT * FROM badges ORDER BY id LIMIT ? OFFSET ?',[i.limit,i.offset]) },
 create_badge: { description:'Create a generic badge.',scope:'configuration',schema:z.object({name:z.string().trim().min(1).max(100),icon:z.string().max(20).default(''),color:z.string().regex(/^#[a-fA-F0-9]{6}$/),text_color:z.string().regex(/^#[a-fA-F0-9]{6}$/).default('#ffffff'),description:note.default('')}).strict(),run:(e,a,i)=>mutate(e,a,'create_badge',i.name,"INSERT INTO badges(name,icon,color,text_color,shape,description) VALUES (?,?,?,?,'pill',?)",[i.name,i.icon,i.color,i.text_color,i.description]) },
 update_badge: { description:'Update a generic badge.',scope:'configuration',schema:z.object({id,name:z.string().trim().min(1).max(100),icon:z.string().max(20),color:z.string().regex(/^#[a-fA-F0-9]{6}$/),text_color:z.string().regex(/^#[a-fA-F0-9]{6}$/),description:note}).strict(),run:(e,a,i)=>mutate(e,a,'update_badge',`badge:${i.id}`,'UPDATE badges SET name=?,icon=?,color=?,text_color=?,description=? WHERE id=?',[i.name,i.icon,i.color,i.text_color,i.description,i.id]) },
 assign_badge: { description:'Assign or remove a badge on a member.',scope:'members',schema:z.object({user_id:id,badge_id:id,assigned:z.boolean(),status:z.enum(['have','need']).default('have')}).strict(),run:(e,a,i)=>i.assigned?mutate(e,a,'assign_badge',`user:${i.user_id}/badge:${i.badge_id}`,"INSERT INTO user_badges(user_id,badge_id,status) VALUES (?,?,?) ON CONFLICT(user_id,badge_id) DO UPDATE SET status=excluded.status",[i.user_id,i.badge_id,i.status]):mutate(e,a,'remove_badge',`user:${i.user_id}/badge:${i.badge_id}`,'DELETE FROM user_badges WHERE user_id=? AND badge_id=?',[i.user_id,i.badge_id]) },
 list_topics: { description:'List forum topics, including moderation state.',scope:'read',schema:z.object({...pagination,room_id:id.optional()}).strict(),run:(e,_,i)=>rows(e,'SELECT id,short_id,room_id,user_id,title,content,status,is_pinned,is_locked,deleted_at,removed_at FROM topics WHERE (? IS NULL OR room_id=?) ORDER BY id DESC LIMIT ? OFFSET ?',[i.room_id??null,i.room_id??null,i.limit,i.offset]) },
 list_replies: { description:'List replies in a topic.',scope:'read',schema:z.object({...pagination,topic_id:id}).strict(),run:(e,_,i)=>rows(e,'SELECT id,topic_id,user_id,content,status,deleted_at,removed_at FROM posts WHERE topic_id=? ORDER BY id LIMIT ? OFFSET ?',[i.topic_id,i.limit,i.offset]) },
 create_topic: { description:'Publish a new topic as the authenticated token owner.',scope:'content',schema:z.object({room_id:id,title:z.string().trim().min(1).max(200),content:text}).strict(),run:async(e,a,i)=>{
 const short=crypto.randomUUID().replace(/-/g,'').slice(0,12);
 return mutate(e,a,'create_topic',short,"INSERT INTO topics(room_id,user_id,title,content,short_id,status) SELECT id,?,?,?,?, 'approved' FROM rooms WHERE id=? AND is_locked=0 AND kind!='chat'",[a.id,i.title,i.content,short,i.room_id]); } },
 create_reply: { description:'Publish a reply as the authenticated token owner.',scope:'content',schema:z.object({topic_id:id,content:text}).strict(),run:async(e,a,i)=>{
 const result=await e.DB.batch([e.DB.prepare("INSERT INTO posts(topic_id,user_id,content,status) SELECT t.id,?,?,'approved' FROM topics t JOIN rooms r ON r.id=t.room_id WHERE t.id=? AND t.is_locked=0 AND r.is_locked=0 AND t.status='approved' AND t.deleted_at IS NULL AND t.removed_at IS NULL RETURNING id,content,user_id").bind(a.id,i.content,i.topic_id),e.DB.prepare("UPDATE topics SET reply_count=reply_count+changes(),last_reply_at=CASE WHEN changes()>0 THEN datetime('now') ELSE last_reply_at END WHERE id=?").bind(i.topic_id),auditStatement(e,a,'create_reply',`topic:${i.topic_id}`)]);
 const post=result[0]?.results[0] as {id:number;content:string;user_id:number}|undefined;
 if(post) {const topic=await e.DB.prepare('SELECT id,short_id,title,user_id FROM topics WHERE id=?').bind(i.topic_id).first<{id:number;short_id:string;title:string;user_id:number|null}>();if(topic)try{await notifyMentionsAndFollowers(e,topic,post,a.id);}catch{/* notifications are best effort, matching the browser post path */}}
 return {changed:result[0]?.meta.changes??0,id:post?.id}; } },
 edit_content: { description:'Edit a topic or reply with a recorded administrator action.',scope:'content',schema:z.object({type:z.enum(['topic','post']),id,content:text}).strict(),run:(e,a,i)=>mutate(e,a,'edit_content',`${i.type}:${i.id}`,`UPDATE ${i.type==='topic'?'topics':'posts'} SET content=?,updated_at=datetime('now') WHERE id=?`,[i.content,i.id]) },
 moderate_content: { description:'Approve, reject, hide or restore a topic/reply and refresh reply counts.',scope:'moderation',schema:z.object({type:z.enum(['topic','post']),id,action:z.enum(['approve','reject','hide','restore'])}).strict(),run:async(e,a,i)=>{
 const table=i.type==='topic'?'topics':'posts';
 const clause=i.action==='approve'?"status='approved'":i.action==='reject'?"status='rejected'":i.action==='hide'?"removed_at=datetime('now'),removed_by=?":"removed_at=NULL,removed_by=NULL,deleted_at=NULL,deleted_by=NULL,delete_reason=NULL";
 const values=i.action==='hide'?[a.id,i.id]:[i.id];
 const result=await e.DB.batch([e.DB.prepare(`UPDATE ${table} SET ${clause} WHERE id=?`).bind(...values),e.DB.prepare("UPDATE topics SET reply_count=(SELECT count(*) FROM posts WHERE posts.topic_id=topics.id AND status='approved' AND deleted_at IS NULL AND removed_at IS NULL) WHERE id=? OR id=(SELECT topic_id FROM posts WHERE id=?)").bind(i.type==='topic'?i.id:0,i.type==='post'?i.id:0),auditStatement(e,a,i.action,`${i.type}:${i.id}`),e.DB.prepare('INSERT INTO mod_logs(mod_id,action,target_type,target_id,details) VALUES (?,?,?,?,NULL)').bind(a.id,i.action,i.type,i.id)]);return {changed:result[0]?.meta.changes??0}; } },
 list_reports: { description:'List reports without reading private conversations.',scope:'moderation',schema:z.object(pagination).strict(),run:(e,_,i)=>rows(e,"SELECT id,reporter_id,content_type,content_id,reason,detail,status FROM reports WHERE content_type IN ('topic','post','user') ORDER BY id DESC LIMIT ? OFFSET ?",[i.limit,i.offset]) },
 resolve_report: { description:'Resolve or dismiss a pending report.',scope:'moderation',schema:z.object({id,status:z.enum(['resolved','dismissed']),note}).strict(),run:(e,a,i)=>mutate(e,a,'resolve_report',`report:${i.id}`,"UPDATE reports SET status=?,resolved_by=?,resolved_at=datetime('now'),resolution_note=? WHERE id=? AND status='pending'",[i.status,a.id,i.note,i.id]) },
 list_warnings: { description:'List moderation warnings about public content and member behavior.',scope:'moderation',schema:z.object(pagination).strict(),run:(e,_,i)=>rows(e,"SELECT * FROM warnings WHERE target_type IN ('user','topic','post') ORDER BY id DESC LIMIT ? OFFSET ?",[i.limit,i.offset]) },
 warn_member: { description:'Issue a warning and notify the member.',scope:'moderation',schema:z.object({user_id:id,message:text}).strict(),run:async(e,a,i)=>{
 const result=await e.DB.batch([e.DB.prepare("INSERT INTO warnings(user_id,mod_id,target_type,target_content) VALUES (?,?,'user',?)").bind(i.user_id,a.id,i.message),e.DB.prepare("INSERT INTO notifications(user_id,content,url,type) VALUES (?,?,'/settings/warnings','warning')").bind(i.user_id,i.message),auditStatement(e,a,'warn_member',`user:${i.user_id}`)]);return {changed:result[0]?.meta.changes??0}; } },
 resolve_warning: { description:'Resolve a moderation warning.',scope:'moderation',schema:z.object({id,note}).strict(),run:(e,a,i)=>mutate(e,a,'resolve_warning',`warning:${i.id}`,"UPDATE warnings SET resolved_at=datetime('now'),resolved_by=?,resolve_memo=? WHERE id=? AND resolved_at IS NULL",[a.id,i.note,i.id]) },
 list_appeals: { description:'List ban appeals.',scope:'moderation',schema:z.object(pagination).strict(),run:(e,_,i)=>rows(e,'SELECT * FROM ban_appeals ORDER BY id DESC LIMIT ? OFFSET ?',[i.limit,i.offset]) },
 resolve_appeal: { description:'Approve or reject a pending ban appeal; approval removes the ban.',scope:'moderation',schema:z.object({id,status:z.enum(['approved','rejected']),note}).strict(),run:async(e,a,i)=>{
 const result=await e.DB.batch([e.DB.prepare("UPDATE ban_appeals SET status=?,mod_id=?,mod_note=?,resolved_at=datetime('now') WHERE id=? AND status='pending'").bind(i.status,a.id,i.note,i.id),e.DB.prepare("UPDATE users SET is_banned=0 WHERE id=(SELECT user_id FROM ban_appeals WHERE id=? AND status='approved' AND mod_id=?) AND ?='approved'").bind(i.id,a.id,i.status),auditStatement(e,a,'resolve_appeal',`appeal:${i.id}`)]);return {changed:result[0]?.meta.changes??0}; } },
 audit_history: { description:'Read administrator API audit history.',scope:'read',schema:z.object(pagination).strict(),run:(e,_,i)=>rows(e,'SELECT * FROM admin_api_audit ORDER BY id DESC LIMIT ? OFFSET ?',[i.limit,i.offset]) },
 prepare_delete: { description:'Preview a permanent deletion and issue a five-minute confirmation. Deletion requires a separate confirm call.',scope:'delete',schema:z.object({type:targetType,id}).strict(),run:(e,a,i)=>prepareDeletion(e,a,i.type,i.id) },
 confirm_delete: { description:'Permanently delete the matching target with its single-use preparation token.',scope:'delete',schema:z.object({type:targetType,id,confirmation:z.string().regex(/^extb_[a-f0-9]{64}$/)}).strict(),run:(e,a,i)=>confirmDeletion(e,a,i.type,i.id,i.confirmation) },
};
export async function runAdminOperation(env: Env, actor: AdminActor, name: string, input: unknown): Promise<unknown> {
 const operation=adminOperations[name];
 if (!operation) throw new Error('Unknown operation');
 await authorize(env,actor,operation.scope);
 return operation.run(env,actor,operation.schema.parse(input));
}
