/** UI-only translations: authored strings never enter this dictionary. */
export type Locale = 'en' | 'he';
export const HEBREW: Readonly<Record<string, string>> = {
"reply":"תגובה", "replies":"תגובות", "topics":"דיונים",
"most recently updated": "העדכונים האחרונים",
"You clicked Members - that directory opens once your intro is approved.":"לחצת על חברי הקהילה — הרשימה תיפתח לאחר אישור ההיכרות שלך.","We've sent a verification link to your email address. Click it to activate your account.":"שלחנו קישור אימות לכתובת הדוא״ל שלך. יש ללחוץ עליו כדי להפעיל את החשבון.","Check your spam folder if you don't see it.":"אם ההודעה לא הגיעה, כדאי לבדוק בתיקיית דואר הזבל.","Resend to":"שליחה מחדש אל","Already verified?":"כבר אימתת את החשבון?","If your account has email recovery enabled, we have sent a reset link. Otherwise, ask your community administrator for a private reset link.":"אם שחזור בדוא״ל מופעל בחשבון שלך, שלחנו קישור לאיפוס. אחרת, אפשר לבקש ממנהל הקהילה קישור פרטי לאיפוס.","Choose new password":"בחירת סיסמה חדשה","Your password has been successfully reset.":"הסיסמה שלך אופסה בהצלחה.","3-32 chars, letters/numbers/underscore/hyphen only.":"3–32 תווים, אותיות באנגלית, ספרות, קו תחתון או מקף בלבד.","Permanent after saving.":"לא ניתן לשנות לאחר השמירה.","Pick one below or type your own":"בחירת הצעה למטה או הקלדת שם משלך","+ More suggestions":"+ הצעות נוספות","Used for chat timestamps and post dates.":"משמש להצגת שעות בצ׳אט ותאריכי פרסומים.","Welcome to our community":"ברוכים הבאים לקהילה שלנו","A place to share ideas, ask questions, meet people, and keep the conversation going.":"מקום לשיתוף רעיונות, לשאלות, להיכרות עם אנשים ולהמשך השיחה.","Explore the discussion rooms, join live chat, and make yourself at home.":"אפשר לגלות את חדרי הדיון, להצטרף לצ׳אט ולהרגיש בבית.","Read the community guidelines":"קריאת כללי הקהילה","Community rules":"כללי הקהילה","Your account and content":"החשבון והתוכן שלך","You remain responsible for your contributions. Do not post material you have no right to share. Keep your password private. Community administrators may moderate content and restrict accounts to enforce these rules.":"האחריות לפרסומים שלך נשארת שלך. אין לפרסם חומר שאין לך זכות לשתף. יש לשמור את הסיסמה בסוד. מנהלי הקהילה יכולים לנהל תוכן ולהגביל חשבונות כדי לאכוף את הכללים.","This installation is operated by its community owner. Contact your community administrators for privacy, account, or moderation questions.":"הקהילה מופעלת בידי הבעלים שלה. לשאלות על פרטיות, חשבון או ניהול תוכן, יש לפנות למנהלי הקהילה.","Community Guidelines &amp; Terms of Use":"כללי הקהילה ותנאי השימוש","Contents":"תוכן עניינים","TL;DR":"בקצרה","The short version &mdash; the full text below is what governs.":"הגרסה הקצרה — הנוסח המלא בהמשך הוא הקובע.","Respect each other":"כבוד הדדי","No harassment, hate, spam, or illegal content.":"אין מקום להטרדה, לשנאה, לדואר זבל או לתוכן לא חוקי.","Protect privacy":"שמירה על פרטיות","Share only information you have permission to share.":"יש לשתף רק מידע שיש לך רשות לשתף.","Moderators can remove content and restrict access. Report issues through the community tools.":"מנהלי הקהילה יכולים להסיר תוכן ולהגביל גישה. אפשר לדווח על בעיות דרך כלי הקהילה.","The Community Guidelines have been updated.":"כללי הקהילה עודכנו.","Please review and acknowledge to continue participating.":"יש לקרוא ולאשר כדי להמשיך להשתתף.","Review &amp; accept":"קריאה ואישור","Community Guidelines - TL;DR":"כללי הקהילה — בקצרה","Read full guidelines ▾":"קריאת הכללים המלאים ▾","I understand &mdash; accept and continue":"הבנתי — אישור והמשך","I understand - accept and continue":"הבנתי — אישור והמשך","Read and accept the Community Guidelines":"קריאה ואישור של כללי הקהילה","Last updated:":"עדכון אחרון:","Version":"גרסה",
"Your community is ready. Join a conversation or introduce yourself.":"הקהילה שלך מוכנה. אפשר להצטרף לשיחה או להציג את עצמך.","Trusted membership is required for this room.":"הכניסה לחדר הזה דורשת חברות מלאה ומאומתת.","Online":"מחוברים","No one yet":"עדיין אין משתתפים","Hide chat":"הסתרת צ׳אט","Make chat larger":"הגדלת הצ׳אט","Larger":"הגדלה","Close":"סגירה","Cancel reply":"ביטול תגובה","Replying to":"תגובה אל","Add reaction":"הוספת תגובה רגשית","Posts:":"פרסומים:","Comments:":"תגובות:","offline":"לא מחובר/ת","mobile notifications":"התראות בנייד","An email verification link activates your account.":"קישור אימות בדוא״ל מפעיל את החשבון שלך.","Welcome! Please choose your public identity. Your display name is":"ברוכים הבאים! יש לבחור את הזהות הציבורית שלך. שם התצוגה שלך הוא","permanent":"קבוע",
"Connecting…":"מתחברים…","Type a message, or / for commands":"כתיבת הודעה, או / לפקודות","Trusted member":"חבר/ה מלא/ה","member":"חבר/ה","full":"חבר/ה מלא/ה","mod":"מנהל/ת","admin":"מנהל/ת ראשי/ת","online":"מחוברים","Send failed.":"השליחה נכשלה.",
  "Login": "כניסה",
  "Log in": "כניסה",
  "Register": "הרשמה",
  "Logout": "יציאה",
  "Create Account": "יצירת חשבון",
  "Create an account": "יצירת חשבון",
  "Email": "דוא״ל",
  "Email or Username": "דוא״ל או שם משתמש",
  "Password": "סיסמה",
  "Password (min 8 chars)": "סיסמה (לפחות 8 תווים)",
  "Forgot password?": "שכחת את הסיסמה?",
  "Already have an account?": "כבר יש לך חשבון?",
  "Username": "שם משתמש",
  "Display Name": "שם תצוגה",
  "Display name": "שם תצוגה",
  "Confirm": "אישור",
  "Members": "חברי הקהילה",
  "Chat": "צ׳אט",
  "Feed": "עדכונים",
  "Needs you": "מחכים לתשובה",
  "Most Recent": "העדכונים האחרונים",
  "Main": "ראשי",
  "Rooms": "חדרים",
  "Private": "פרטי",
  "Learn": "מידע",
  "Community Guidelines": "כללי הקהילה",
  "Profile": "פרופיל",
  "Settings": "הגדרות",
  "Notifications": "התראות",
  "Inbox": "הודעות נכנסות",
  "Direct messages": "הודעות פרטיות",
  "Search": "חיפוש",
  "Search...": "חיפוש...",
  "Search Results": "תוצאות חיפוש",
  "Loading...": "טוען...",
  "Skip to content": "דילוג לתוכן",
  "Home": "בית",
  "About": "אודות",
  "New Topic": "דיון חדש",
  "+ New Topic": "+ דיון חדש",
  "Start a discussion": "פתיחת דיון",
  "Join the Discussion": "הצטרפות לדיון",
  "Title": "כותרת",
  "Message": "הודעה",
  "Post": "פרסום",
  "Post Reply": "פרסום תגובה",
  "Reply": "תגובה",
  "Send Reply": "שליחת תגובה",
  "Submit Reply": "שליחת תגובה",
  "Submit for review": "שליחה לאישור",
  "Edit Post": "עריכת תגובה",
  "Edit Topic": "עריכת דיון",
  "Cancel": "ביטול",
  "Save": "שמירה",
  "Save Changes": "שמירת שינויים",
  "Remove": "הסרה",
  "Delete": "מחיקה",
  "Restore": "שחזור",
  "Tags": "תגיות",
  "Options": "אפשרויות",
  "Cast Vote": "הצבעה",
  "✓ Your vote": "✓ ההצבעה שלך",
  "📊 Add a Poll": "📊 הוספת סקר",
  "(one per line, minimum 2)": "(אחת בשורה, לפחות שתיים)",
  "(optional)": "(לא חובה)",
  "(comma separated)": "(מופרדות בפסיקים)",
  "No topics yet.": "אין עדיין דיונים.",
  "No replies yet.": "אין עדיין תגובות.",
  "No messages yet. Say hi.": "אין עדיין הודעות. אפשר להגיד שלום.",
  "No conversations yet.": "אין עדיין שיחות.",
  "No notifications yet.": "אין עדיין התראות.",
  "No users found.": "לא נמצאו משתמשים.",
  "No posts yet": "אין עדיין פרסומים",
  "No rooms yet.": "אין עדיין חדרים.",
  "No questions yet.": "אין עדיין שאלות.",
  "Nothing waiting": "אין פניות שממתינות",
  "Everyone's been answered.": "כולם קיבלו תשובה.",
  "Load more topics": "טעינת דיונים נוספים",
  "More results": "תוצאות נוספות",
  "Latest Replies": "תגובות אחרונות",
  "Latest Topics": "דיונים אחרונים",
  "Top Topics": "דיונים מובילים",
  "Top Contributors": "משתתפים מובילים",
  "Recent Activity": "פעילות אחרונה",
  "Topics Started": "דיונים שנפתחו",
  "Mark all read": "סימון הכל כנקרא",
  "Mark all threads read": "סימון כל הדיונים כנקראו",
  "Open menu": "פתיחת תפריט",
  "Close menu": "סגירת תפריט",
  "Account menu": "תפריט חשבון",
  "Primary": "ניווט ראשי",
  "Rooms and pages": "חדרים ודפים",
  "New topic": "דיון חדש",
  "Text size": "גודל טקסט",
  "Change text size": "שינוי גודל הטקסט",
  "Toggle Theme": "שינוי ערכת צבעים",
  "Toggle dark mode": "שינוי מצב כהה",
  "Open chat": "פתיחת צ׳אט",
  "Close chat": "סגירת צ׳אט",
  "Chat is open in the panel": "הצ׳אט פתוח בלוח הצד",
  "It stays open while you browse. Use the Chat button to show or hide it.": "הצ׳אט נשאר פתוח בזמן הגלישה. כפתור הצ׳אט מציג או מסתיר אותו.",
  "Send": "שליחה",
  "Type a message...": "כתיבת הודעה...",
  "typing…": "מקלידים…",
  "Me": "אני",
  "DMs": "הודעות",
  "Ask a question": "שאלת שאלה",
  "Recent questions": "שאלות אחרונות",
  "Want to join the conversation?": "רוצה להצטרף לשיחה?",
  "Want to read and participate in discussions?": "רוצה לקרוא ולהשתתף בדיונים?",
  "Introduce yourself": "הצגה עצמית",
  "Profile Picture": "תמונת פרופיל",
  "Edit Profile": "עריכת פרופיל",
  "Bio": "אודותיי",
  "Personal Bio": "אודותיי",
  "Preferred Pronouns": "לשון פנייה מועדפת",
  "Pronouns": "לשון פנייה",
  "Website": "אתר",
  "Personal Website": "אתר אישי",
  "Timezone": "אזור זמן",
  "Local Timezone": "אזור זמן מקומי",
  "Account Settings": "הגדרות חשבון",
  "Social & Privacy": "קשרים ופרטיות",
  "Public Identity": "זהות ציבורית",
  "Identity": "זהות",
  "Your Badges": "התגים שלך",
  "Search Badges": "חיפוש תגים",
  "Change Photo": "שינוי תמונה",
  "Cover Image": "תמונת כיסוי",
  "Upload Cover": "העלאת תמונת כיסוי",
  "Remove Cover Image": "הסרת תמונת כיסוי",
  "Remove Profile Picture": "הסרת תמונת פרופיל",
  "Hide bio from public profile": "הסתרת הביוגרפיה מהפרופיל הציבורי",
  "Hide activity from public profile": "הסתרת הפעילות מהפרופיל הציבורי",
  "Allow others to start direct messages with me": "אפשרות לאחרים לשלוח לי הודעות פרטיות",
  "Save Account Changes": "שמירת שינויי חשבון",
  "Delete My Account": "מחיקת החשבון שלי",
  "Update password": "עדכון סיסמה",
  "New password (min 8 chars)": "סיסמה חדשה (לפחות 8 תווים)",
  "Reset password": "איפוס סיסמה",
  "Send reset link": "שליחת קישור לאיפוס",
  "Check your email": "יש לבדוק את הדוא״ל",
  "Log in now": "כניסה עכשיו",
  "Log in to Reply": "כניסה כדי להגיב",
  "Confirm your email to access the forum and all features.": "יש לאמת את כתובת הדוא״ל כדי לגשת לקהילה ולכל האפשרויות.",
  "Resend verification email": "שליחת דוא״ל אימות מחדש",
  "Registration Closed": "ההרשמה סגורה",
  "New accounts are not being accepted right now.": "כרגע לא ניתן לפתוח חשבונות חדשים.",
  "Return Home": "חזרה לבית",
  "Follow": "מעקב",
  "Following": "במעקב",
  "View all": "הצגת הכל",
  "Search and add badges. They appear under your profile picture on posts.": "חיפוש והוספת תגים. הם יופיעו מתחת לתמונת הפרופיל בפרסומים.",
  "No bio provided yet.": "עדיין לא נוספה ביוגרפיה.",
  "This user has hidden their bio.": "המשתמש הסתיר את הביוגרפיה שלו.",
  "This user has hidden their activity.": "המשתמש הסתיר את הפעילות שלו.",
  "This room is read-only for your access level.": "בחדר הזה יש לך הרשאת קריאה בלבד.",
  "Posts go to moderator review before appearing.": "הפרסומים נשלחים לאישור מנהל לפני שיופיעו.",
  "Read and accept the Community Guidelines above to enable.": "יש לקרוא ולאשר את כללי הקהילה כדי להמשיך.",
  "User Directory": "חברי הקהילה",
  "Find and connect with members of the community.": "אפשר למצוא חברים מהקהילה ולהכיר.",
  "Enable Notifications": "הפעלת התראות",
  "Send report": "שליחת דיווח",
  "Why are you reporting this?": "מה סיבת הדיווח?",
  "Reports are private - only the mod team sees them.": "הדיווחים פרטיים ורק צוות הניהול רואה אותם.",
  "Name": "שם",
  "Reason (optional)": "סיבה (לא חובה)",
  "Warnings": "אזהרות",
  "No warnings": "אין אזהרות",
  "Moderation": "ניהול",
  "Welcome": "ברוכים הבאים",
  "Finish setup": "השלמת ההגדרה",
  "Set up your profile": "הגדרת הפרופיל",
  "I am 18 or older": "גילי 18 ומעלה",
  "FORUM INDEX": "רשימת חדרים",
  "Community Replies": "תגובות הקהילה",
  "Ctrl+Enter to post": "Ctrl+Enter לפרסום",
  "Posting in": "פרסום בחדר",
  "User": "משתמש",
  "Access level": "רמת הרשאה",
  "Account": "חשבון",
  "+ Add": "+ הוספה"
};
export function resolveLocale(req: Request, fallback: string = 'en'): Locale {
 const query = new URL(req.url).searchParams.get('lang');
 if (query === 'he' || query === 'en') return query;
 const cookie = req.headers.get('cookie')?.match(/(?:^|;\s*)extb_locale=(he|en)(?:;|$)/)?.[1];
 return cookie === 'he' || cookie === 'en' ? cookie : fallback === 'he' ? 'he' : 'en';
}
export function localizeHtml(html: string, locale: string): string {
 // Protect code, scripts, style and editable values even if a marker appears inside.
 const protectedParts: string[] = [];
 let result = html.replace(/<(script|style|textarea|code|pre)\b[^>]*>[\s\S]*?<\/\1>/gi, part => {
  protectedParts.push(part); return `\u0000EXTB_PROTECTED_${protectedParts.length - 1}\u0000`;
 });
 result = result.replace(/<!--extb-ui-->([\s\S]*?)<!--\/extb-ui-->/g, (_all, text: string) => {
  const key = text.trim(); return locale === 'he' && HEBREW[key] ? text.replace(key, HEBREW[key]) : text;
 });
 result = result.replace(/<[a-z][^>]*>/gi, tag => {
   return tag.replace(/ data-extb-i18n-(placeholder|title|aria-label)="([^"<>]*)"/g, (_marker, attr: string, text: string) => '').replace(/(placeholder|title|aria-label)="([^"<>]*)"/g, (original, attr: string, text: string) => {
     const marker = `data-extb-i18n-${attr}="${text}"`;
     return tag.includes(marker) && locale === 'he' && HEBREW[text] ? `${attr}="${HEBREW[text]}"` : original;
   });
 });
 result = result.replace(/<html\b[^>]*>/, `<html lang="${locale === 'he' ? 'he' : 'en'}" dir="${locale === 'he' ? 'rtl' : 'ltr'}">`);
 return result.replace(/\u0000EXTB_PROTECTED_(\d+)\u0000/g, (_all, index: string) => protectedParts[Number(index)] ?? '');
}
export async function localizeResponse(response: Response, locale: Locale, requestUrl?: string): Promise<Response> {
 if (!response.headers.get('Content-Type')?.includes('text/html') || response.status === 101) return response;
 let html = localizeHtml(await response.text(), locale);
 if (requestUrl) html = html.replace(/<a\b[^>]*>/g, tag => {
   const language = tag.match(/data-language="(he|en)"/)?.[1];
   if (!language || !/class="[^"]*\blanguage-switch\b/.test(tag)) return tag;
   const target = new URL(requestUrl); target.searchParams.set('lang', language);
   const relative = target.pathname + target.search + target.hash;
   const escaped = relative.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
   return tag.replace(/href="[^"]*"/, `href="${escaped}"`);
 });
 const result = new Response(html, response);
 result.headers.delete('Content-Length'); result.headers.set('Content-Language', locale);
 return result;
}
