export const wizardScript = String.raw`
const app=document.getElementById('app');app.setAttribute('aria-live','polite');
const he=navigator.language.toLowerCase().startsWith('he');document.documentElement.dir=he?'rtl':'ltr';
const labels=he?{name:'שם הקהילה',purpose:'מטרת הקהילה במשפט אחד',preview:'תצוגה מקדימה',install:'אישור ויצירת הקהילה',edit:'עריכת התוכן',retry:'ניסיון חוזר',open:'יצירת חשבון בעלים',account:'חשבון Cloudflare'}:{name:'Community name',purpose:'Purpose in one sentence',preview:'Preview',install:'Approve and create community',edit:'Edit content',retry:'Retry',open:'Create owner account',account:'Cloudflare account'};
let session=await (await fetch('/api/session')).json(),draft;
async function api(path,body){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':session.csrf},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error||'Request failed');return value;}
function element(tag,text,parent=app){const e=document.createElement(tag);if(text)e.textContent=text;parent.append(e);return e;}
function error(e){element('p',e.message);}
function start(){app.replaceChildren();const form=element('form');let account;
if(session.accounts.length>1){element('label',labels.account,form);account=element('select',null,form);for(const a of session.accounts){const option=element('option',a.name,account);option.value=a.id;}}
element('label',labels.name,form).htmlFor='community-name';const name=element('input',null,form);name.id='community-name';name.required=true;name.maxLength=80;name.placeholder=labels.name;name.setAttribute('aria-label',labels.name);
element('label',labels.purpose,form).htmlFor='community-purpose';const purpose=element('input',null,form);purpose.id='community-purpose';purpose.required=true;purpose.maxLength=300;purpose.placeholder=labels.purpose;purpose.setAttribute('aria-label',labels.purpose);
element('label',he?'סוג הקהילה':'Community type',form).htmlFor='community-type';const preset=element('select',null,form);preset.id='community-type';preset.setAttribute('aria-label','Community type');for(const [value,en,heName] of [['general','General community','קהילה כללית'],['club','Club / local group','מועדון / קבוצה מקומית'],['creator','Creator community','קהילת יוצרים'],['project','Project community','קהילת פרויקט'],['support','Support community','קהילת תמיכה']]){const o=element('option',he?heName:en,preset);o.value=value;}
element('label',he?'שפה':'Language',form).htmlFor='community-language';const language=element('select',null,form);language.id='community-language';language.setAttribute('aria-label','Language');for(const [value,label] of [['en','English'],['he','עברית']]){const o=element('option',label,language);o.value=value;}language.value=he?'he':'en';
const submit=element('button',labels.preview,form);submit.type='submit';form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{const result=await api('/api/preview',{input:{name:name.value,purpose:purpose.value,preset:preset.value,language:language.value}});draft=result.draft;preview(result.html,account?.value||session.accounts[0].id);}catch(e){error(e);}finally{submit.disabled=false;}};}
function preview(html,account){app.replaceChildren();const view=element('section');view.innerHTML=html;const details=element('details');element('summary',labels.edit,details);const editor=element('textarea',JSON.stringify(draft,null,2),details);editor.rows=24;editor.cols=70;editor.setAttribute('aria-label',labels.edit);const update=element('button',labels.preview,details);update.onclick=async()=>{try{const result=await api('/api/preview',{draft:JSON.parse(editor.value)});draft=result.draft;view.innerHTML=result.html;editor.value=JSON.stringify(draft,null,2);approve.disabled=false;}catch(e){error(e);}};
const approve=element('button',labels.install);element('p',he?'לאחר עריכה יש לעדכן את התצוגה לפני אישור.':'After editing, update the preview before approving.',details);editor.oninput=()=>{approve.disabled=true;};approve.onclick=async()=>{approve.disabled=true;try{await api('/api/install',{account,draft});status();}catch(e){error(e);approve.disabled=false;}};}
async function status(){app.replaceChildren();const job=await (await fetch('/api/status')).json();element('p',job.stage);for(const stage of job.completed)element('p','✓ '+stage);if(job.error){element('p',job.error);const retry=element('button',labels.retry);retry.onclick=async()=>{retry.disabled=true;try{await api('/api/retry',{});status();}catch(e){error(e);retry.disabled=false;}};const dashboard=element('a','Cloudflare dashboard');dashboard.href=job.dashboard;}
else if(job.stage==='complete'){const open=element('button',labels.open);open.onclick=async()=>{try{const result=await api('/api/handoff',{});location.assign(result.url);}catch(e){error(e);const auth=element('a',he?'הרשאה חדשה לפתיחת ההגדרה':'Authorize again to reopen setup');auth.href='/oauth/start';}};const another=element('a',he?'יצירת קהילה נוספת':'Create another community');another.href='/oauth/start?new=1';session=await (await fetch('/api/session')).json();githubPanel(job);}
else setTimeout(status,1500);}
function githubPanel(job){if(!session.githubConfigured)return;const panel=element('details');element('summary',he?'חיבור GitHub (אופציונלי)':'Connect GitHub (optional)',panel);element('p',he?'הפורום כבר מותקן. חיבור GitHub מאפשר עדכונים דרך מאגר פרטי. Cloudflare דורשת אישור חד־פעמי לאפליקציית GitHub שלה. המאגר משתמש בתבנית EXTB העדכנית; הבנייה הראשונה מעדכנת את הקוד ומחילה מיגרציות למסד הנתונים.':'Your forum is installed. GitHub connects a private repository for future updates. Cloudflare requires one-time authorization of its GitHub App. The repository uses the current EXTB template; its first build updates forum code and applies database migrations.',panel);
if(!session.cloudflareAuthorized){const auth=element('a',he?'הרשאה חדשה ב-Cloudflare':'Authorize Cloudflare again',panel);auth.href='/oauth/start';return;}
if(session.github?.connection){const repository=element('a',session.github.connection.repositoryUrl,panel);repository.href=session.github.connection.repositoryUrl;if(session.github.lastBuild)element('p',(he?'מזהה בנייה: ':'Build ID: ')+session.github.lastBuild.id,panel);const logs=element('button',he?'בדיקת מצב הבנייה':'Check build status',panel);const build=element('button',he?'הפעלת בנייה ופריסה':'Start build and deployment',panel);function renew(){logs.disabled=true;build.disabled=true;const auth=element('a',he?'הרשאה חדשה להמשך פעולות':'Authorize again for further actions',panel);auth.href='/oauth/start';}logs.onclick=async()=>{logs.disabled=true;try{const result=await api('/api/github/status',{});element('pre',JSON.stringify(result.builds,null,2),panel);}catch(e){error(e);}finally{renew();}};build.onclick=async()=>{build.disabled=true;try{const result=await api('/api/github/build',{});element('p',(he?'הבנייה התחילה: ':'Build started: ')+result.build_uuid,panel);const dashboard=element('a','Cloudflare Builds',panel);dashboard.href=session.github.connection.dashboard;}catch(e){error(e);}finally{renew();}};return;}
if(!session.github?.authorized){const auth=element('button',he?'הרשאה ב-GitHub':'Authorize GitHub',panel);auth.onclick=async()=>{try{const result=await api('/api/github/start',{});location.assign(result.url);}catch(e){error(e);}};return;}
element('label',he?'שם המאגר הפרטי':'Private repository name',panel).htmlFor='repo-name';const name=element('input',null,panel);name.id='repo-name';name.value=session.github.progress.repositoryName||job.worker;const create=element('button',he?'יצירת המאגר':'Create repository',panel);create.onclick=async()=>{create.disabled=true;try{const result=await api('/api/github/connect',{repositoryName:name.value});const repo=element('a',result.repository,panel);repo.href=result.repository;element('p',result.action,panel);const dashboard=element('a','Cloudflare Settings → Builds',panel);dashboard.href=result.dashboard;deployToken();}catch(e){error(e);create.disabled=false;}};
function deployToken(){element('label',he?'מזהה אסימון פריסה מ-Cloudflare Builds':'Cloudflare Builds deployment token ID',panel).htmlFor='build-token';const token=element('input',null,panel);token.id='build-token';const connect=element('button',he?'חיבור לפריסות עתידיות':'Connect future deployments',panel);connect.onclick=async()=>{connect.disabled=true;try{const result=await api('/api/github/connect',{repositoryName:name.value,buildTokenId:token.value});element('p',he?'החיבור הוגדר. יש לבדוק שהבנייה והפריסה מצליחות ב-Cloudflare.':'Connection configured. Check that the build and deployment succeed in Cloudflare.',panel);const dashboard=element('a','Cloudflare Builds',panel);dashboard.href=result.connection.dashboard;}catch(e){error(e);connect.disabled=false;}};}if(session.github.progress.configured)deployToken();}
if(session.job)status();else if(!session.accounts?.length)element('p','No authorized Cloudflare accounts. Authorize access to an account and try again.');else start();
`;
