name = "extb2"
main = "src/index.ts"
compatibility_date = "2026-10-02"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "extb-community"
database_id = "60b5d29e-f47e-47b9-9194-505e587b842c"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "PASSWORD_HASHER"
class_name = "PasswordHasher"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom", "PasswordHasher"]

[vars]
BUILD_ID = "extb-v1"
