import {describe,it,expect,vi,afterEach} from 'vitest';
import {randomToken,digest,hexDigest,equal,seal,unseal} from '../installer/src/security';
import {releaseURL,checkedFile,upload} from '../installer/src/cloudflare';
import {Installation} from '../installer/src/index';
import {makeCommunityDraft} from '../src/community/draft';
const origin='https://extb.achiron.fyi';
const stages=['account checks','database creation','migrations','ownership authorization','Worker deployment','readiness'];
const secret='a'.repeat(43);
function harness(session:unknown){let stored=session;const records=new Map<string,unknown>();const storage={get:vi.fn(async(key:string)=>structuredClone(key==='session'?stored:records.get(key))),put:vi.fn(async(key:string,v:unknown)=>{if(key==='session')stored=structuredClone(v);else records.set(key,structuredClone(v));}),setAlarm:vi.fn(async()=>{}),deleteAll:vi.fn(async()=>{}),delete:vi.fn(async()=>{stored=undefined;return true;})};const pending:Promise<unknown>[]=[];const state={storage,waitUntil:(promise:Promise<unknown>)=>pending.push(promise)} as unknown as DurableObjectState;const env={INSTALLER_ORIGIN:origin,ENCRYPTION_KEY:secret,OAUTH_CLIENT_ID:'client',INSTALLATIONS:{} as DurableObjectNamespace,OAUTH_SCOPE:'openid',RELEASE_MANIFEST_URL:'',RELEASE_MANIFEST_SHA256:''};const installation=new Installation(state,env);return {installation,storage,finish:async()=>{for(let i=0;i<10;i++){await installation.alarm();const s=stored as {job?:{stage:string;error?:string}};if(!s?.job || s.job.error || s.job.stage==='complete')break;}},session:()=>stored};}
afterEach(()=>vi.unstubAllGlobals());
describe('installer credential security',()=>{
 it('generates PKCE entropy and known SHA256 digest',async()=>{expect(randomToken()).toMatch(/^[A-Za-z0-9_-]{43}$/);expect(await digest('abc')).toBe('ungWv48Bz-pBQUDeXa4iI7ADYaOWF3qctBD_YfIAFa0');expect(await hexDigest(new TextEncoder().encode('abc').buffer as ArrayBuffer)).toHaveLength(64);expect(equal('abc','abcd')).toBe(false);});
 it('encrypts credentials and rejects tampering or incorrect keys',async()=>{const encrypted=await seal('private-cloudflare-token',secret);expect(encrypted).not.toContain('private');expect(await unseal(encrypted,secret)).toBe('private-cloudflare-token');await expect(unseal(encrypted,'b'.repeat(43))).rejects.toThrow();await expect(unseal(encrypted.slice(0,-3)+'aaa',secret)).rejects.toThrow();});
 it('only accepts pinned public EXTB release URLs',()=>{expect(releaseURL('https://github.com/royachiron/extb/releases/download/v1.2.3/extb-manifest.json')).toBe(true);for(const url of ['https://evil.test/royachiron/extb/releases/download/v1.2.3/x','https://github.com/other/extb/releases/download/v1.2.3/x','https://github.com/royachiron/extb/releases/download/latest/x'])expect(releaseURL(url)).toBe(false);});
 it('rejects checksum mismatches',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response('modified')));await expect(checkedFile('https://github.com/royachiron/extb/releases/download/v1.2.3/x','0'.repeat(64))).rejects.toThrow('checksum');});
 it('retries a lost deployment response without recreating Durable Object namespaces',async()=>{
  const bytes=new TextEncoder().encode('export default {}').buffer as ArrayBuffer;const release={version:'v1.2.3',mainModule:'index.js',modules:[{name:'index.js',url:'https://github.com/royachiron/extb/releases/download/v1.2.3/index.js',sha256:await hexDigest(bytes),type:'esm'}],migrations:[],assets:{manifest:{},files:[]}};let deployed=false;const metadata:Record<string,unknown>[]=[];
  vi.stubGlobal('fetch',vi.fn(async(url:string,init?:RequestInit)=>{if(url.startsWith('https://github.com/'))return new Response(bytes);if(url.endsWith('/assets-upload-session'))return Response.json({success:true,result:{jwt:'completion',buckets:[]}});if(url.endsWith('/workers/scripts'))return Response.json({success:true,result:deployed?[{id:'extb-worker',migration_tag:'v1'}]:[]});if(url.endsWith('/scripts/extb-worker') && init?.method==='PUT'){metadata.push(JSON.parse((init.body as FormData).get('metadata') as string));if(!deployed){deployed=true;throw Error('lost response');}}return Response.json({success:true,result:{}});}));
  await expect(upload('token','a'.repeat(32),'extb-worker','database',release)).rejects.toThrow('lost response');await upload('token','a'.repeat(32),'extb-worker','database',release);expect(metadata[0]?.migrations).toEqual({new_sqlite_classes:['ChatRoom','PasswordHasher'],new_tag:'v1'});expect(metadata[1]?.migrations).toBeUndefined();
 });
 it('refuses preexisting Worker names before creating any database',async()=>{
  const h=harness({expires:Date.now()+60000,csrf:'csrf',subject:'owner',encryptedToken:await seal('token',secret),job:{account:'a'.repeat(32),worker:'extb-collision',databaseName:'extb-collision',stage:'account checks',done:[],draft:{}}});const called:string[]=[];vi.stubGlobal('fetch',vi.fn(async(url:string)=>{called.push(url);return Response.json({success:true,result:[{id:'extb-collision'}]});}));await h.installation.fetch(new Request(origin+'/api/retry',{method:'POST',headers:{Origin:origin,'x-csrf-token':'csrf'},body:'{}'}));await h.finish();expect(called).toHaveLength(1);expect((h.session() as {job:{error:string}}).job.error).toContain('collision');
 });
 it('rejects expired sessions and cross origin writes before any API call',async()=>{const expired=harness({expires:1,csrf:'csrf'});expect((await expired.installation.fetch(new Request(origin+'/api/session'))).status).toBe(401);const live=harness({expires:Date.now()+60000,csrf:'csrf',subject:'owner',encryptedToken:'encrypted'});const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);expect((await live.installation.fetch(new Request(origin+'/api/install',{method:'POST',headers:{Origin:'https://evil.test','x-csrf-token':'csrf'},body:'{}'}))).status).toBe(403);expect(fetcher).not.toHaveBeenCalled();});
 it('consumes OAuth state before cancellation and rejects replay',async()=>{const state='state';const h=harness({expires:Date.now()+60000,csrf:'csrf',state:await digest(state),verifier:'verifier'});const request=()=>new Request(origin+'/oauth/callback?state=state&error=access_denied');expect((await h.installation.fetch(request())).status).toBe(400);expect((await h.installation.fetch(request())).status).toBe(403);});
 it('serializes expiry cleanup with fresh authorization so the new session survives',async()=>{
  const h=harness({expires:1,csrf:'old',subject:'owner',encryptedToken:await seal('token',secret),job:{stage:'complete',done:[],account:'a'.repeat(32),worker:'extb-old'}});let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});const fetcher=vi.fn(async()=>{await gate;return new Response(null,{status:200});});vi.stubGlobal('fetch',fetcher);
  const alarm=h.installation.alarm();await vi.waitFor(()=>expect(fetcher).toHaveBeenCalled());const start=h.installation.fetch(new Request(origin+'/start'));release();await alarm;expect((await start).status).toBe(302);expect((h.session() as {state:string;expires:number}).state).toBeTruthy();expect((h.session() as {expires:number}).expires).toBeGreaterThan(Date.now());
 });
 it('restores installation and GitHub identifiers after expiry without restoring credentials',async()=>{
  const h=harness(undefined);await h.storage.put('installation',{subject:'owner',account:'a'.repeat(32),worker:'extb-existing',database:'database-id',databaseName:'extb-existing',url:'https://extb-existing.example.workers.dev',release:'v1.2.3'});await h.storage.put('github_connection',{progress:{repositoryId:123,repositoryName:'forum',configured:true},connection:{triggerId:'trigger',workerTag:'worker-tag'}});
  const response=await h.installation.fetch(new Request(origin+'/start'));expect(response.status).toBe(302);const session=h.session() as {subject:string;job:{worker:string};encryptedToken?:string;github:{progress:{repositoryId:number};encryptedToken?:string;state?:string}};expect(session.subject).toBe('owner');expect(session.job.worker).toBe('extb-existing');expect(session.github.progress.repositoryId).toBe(123);expect(session.encryptedToken).toBeUndefined();expect(session.github.encryptedToken).toBeUndefined();expect(session.github.state).toBeUndefined();
 });
 it('renews expired ownership only with fresh Cloudflare authorization without changing drafts',async()=>{
  const draft={name:'Original approved draft'},expires=Date.now()+60000,h=harness({expires,csrf:'csrf',subject:'owner',encryptedToken:await seal('token',secret),job:{stage:'complete',done:[],account:'a'.repeat(32),worker:'extb-existing',database:'database-id',url:'https://forum.example.workers.dev',draft,ownershipExpires:1}});let batch:{sql:string;params?:string[]}[]|undefined;
  const fetcher=vi.fn(async(url:string,init?:RequestInit)=>{if(url.endsWith('/revoke'))return new Response(null,{status:200});const body=JSON.parse(init!.body as string);if(body.batch){batch=body.batch;return Response.json({success:true,result:[{success:true},{success:true},{success:true}]});}return Response.json({success:true,result:[{success:true,results:[{complete:0}]}]});});vi.stubGlobal('fetch',fetcher);
  const response=await h.installation.fetch(new Request(origin+'/api/handoff',{method:'POST',headers:{Origin:origin,'x-csrf-token':'csrf'},body:'{}'}));expect(response.status).toBe(200);const value=await response.json() as {url:string};const raw=new URLSearchParams(new URL(value.url).hash.slice(1)).get('ownership')!;expect(raw).toMatch(/^[a-f0-9]{64}$/);expect(batch).toHaveLength(3);expect(batch![0]!.sql).toContain("NOT EXISTS (SELECT 1 FROM settings WHERE key='setup_complete')");expect(batch![0]!.params![0]).toBe(await hexDigest(new TextEncoder().encode(raw).buffer as ArrayBuffer));expect(JSON.stringify(batch)).not.toContain('setup_draft');expect(JSON.stringify(batch)).not.toContain('branding');expect(batch![2]!.sql).toContain('setup_session_hash');const stored=h.session() as {encryptedToken?:string;job:{draft:unknown;ownership:string;ownershipExpires:number}};expect(stored.job.draft).toEqual(draft);expect(stored.job.ownershipExpires).toBe(expires);expect(await unseal(stored.job.ownership,secret)).toBe(raw);expect(stored.encryptedToken).toBeUndefined();expect(fetcher).toHaveBeenCalledTimes(3);
 });
 it('returns an already completed forum without rewriting ownership or community data',async()=>{
  const draft={name:'Approved'},h=harness({expires:Date.now()+60000,csrf:'csrf',subject:'owner',encryptedToken:await seal('token',secret),job:{stage:'complete',done:[],account:'a'.repeat(32),worker:'extb-existing',database:'database-id',url:'https://forum.example.workers.dev',draft}});let writes=0;vi.stubGlobal('fetch',vi.fn(async(url:string,init?:RequestInit)=>{if(url.endsWith('/revoke'))return new Response(null,{status:200});const body=JSON.parse(init!.body as string);if(body.batch)writes++;return Response.json({success:true,result:[{success:true,results:[{complete:1}]}]});}));const response=await h.installation.fetch(new Request(origin+'/api/handoff',{method:'POST',headers:{Origin:origin,'x-csrf-token':'csrf'},body:'{}'}));expect(await response.json()).toEqual({url:'https://forum.example.workers.dev/'});expect(writes).toBe(0);expect((h.session() as {job:{draft:unknown}}).job.draft).toEqual(draft);
 });
 it('requires fresh authorization to renew ownership and reuses a nonexpired initial credential',async()=>{
  const common={expires:Date.now()+60000,csrf:'csrf',subject:'owner',job:{stage:'complete',done:[],account:'a'.repeat(32),worker:'extb-existing',database:'database-id',url:'https://forum.example.workers.dev'}};const h=harness(common),fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);const request=()=>new Request(origin+'/api/handoff',{method:'POST',headers:{Origin:origin,'x-csrf-token':'csrf'},body:'{}'});expect((await h.installation.fetch(request())).status).toBe(409);const initial=harness({...common,job:{...common.job,ownership:await seal('f'.repeat(64),secret),ownershipExpires:Date.now()+60000}});expect(await (await initial.installation.fetch(request())).json()).toEqual({url:'https://forum.example.workers.dev/setup#ownership='+ 'f'.repeat(64)});expect(fetcher).not.toHaveBeenCalled();
 });
 it('does not disclose ownership authorization through status',async()=>{const h=harness({expires:Date.now()+60000,csrf:'csrf',subject:'owner',job:{stage:'complete',done:[],ownership:'SECRET',account:'a',worker:'extb-a'}});const response=await h.installation.fetch(new Request(origin+'/api/status'));expect(await response.text()).not.toContain('SECRET');});
 it('rejects an account outside authenticated authorization',async()=>{const h=harness({expires:Date.now()+60000,csrf:'csrf',subject:'owner',encryptedToken:'encrypted',accounts:[{id:'a'.repeat(32),name:'Authorized'}]});const response=await h.installation.fetch(new Request(origin+'/api/install',{method:'POST',headers:{Origin:origin,'x-csrf-token':'csrf'},body:JSON.stringify({account:'b'.repeat(32),draft:{}})}));expect(response.status).toBe(403);});
 it.each(stages)('retains checkpoint and sanitizes failure at %s',async(stage)=>{
  const index=stages.indexOf(stage),job={account:'a'.repeat(32),worker:'extb-stage',databaseName:'extb-stage',database:'database-id',url:'https://extb-stage.example.workers.dev',stage,done:stages.slice(0,index),draft:{},release:{version:'v1.2.3',mainModule:'index.js',modules:[],migrations:[],assets:{manifest:{},files:[]}}};
  const h=harness({expires:Date.now()+60000,csrf:'csrf',subject:'owner',encryptedToken:await seal('token',secret),job});
  vi.stubGlobal('fetch',vi.fn(async()=>Response.json({success:false,errors:[{code:1001,message:'SECRET_CREDENTIAL_DO_NOT_EXPOSE'}]},{status:503})));
  const response=await h.installation.fetch(new Request(origin+'/api/retry',{method:'POST',headers:{Origin:origin,'x-csrf-token':'csrf'},body:'{}'}));expect(response.status).toBe(202);await h.finish();
  const stored=h.session() as {job:{stage:string;done:string[];error:string}};expect(stored.job.stage).toBe(stage);expect(stored.job.done).toEqual(stages.slice(0,index));expect(stored.job.error).not.toContain('SECRET_CREDENTIAL');expect(stored.job.error).toBeTruthy();
 });
 it('revokes minted OAuth tokens after identity mismatch',async()=>{
  const h=harness({expires:Date.now()+60000,csrf:'csrf',state:await digest('state'),verifier:'verifier',subject:'expected'});const requests:string[]=[];
  vi.stubGlobal('fetch',vi.fn(async(url:string)=>{requests.push(url);if(url.endsWith('/token'))return Response.json({access_token:'secret-token',token_type:'Bearer',expires_in:600});if(url.endsWith('/userinfo'))return Response.json({sub:'attacker'});return new Response(null,{status:200});}));
  const response=await h.installation.fetch(new Request(origin+'/oauth/callback?state=state&code=code'));expect(response.status).toBe(400);expect(requests).toContain('https://dash.cloudflare.com/oauth2/revoke');expect((h.session() as {encryptedToken?:string}).encryptedToken).toBeUndefined();
 });
 it('rejects concurrent duplicate setup requests and gives separate forums unique names',async()=>{
  const init=()=>({expires:Date.now()+60000,csrf:'csrf',subject:'owner',encryptedToken:'',accounts:[{id:'a'.repeat(32),name:'Account'}]});const first=init(),second=init();first.encryptedToken=await seal('token',secret);second.encryptedToken=await seal('token',secret);const h=harness(first),other=harness(second);
  vi.stubGlobal('fetch',vi.fn(async()=>Response.json({success:false,errors:[{code:1001}]},{status:503})));
  const request=()=>new Request(origin+'/api/install',{method:'POST',headers:{Origin:origin,'x-csrf-token':'csrf'},body:JSON.stringify({account:'a'.repeat(32),draft:makeCommunityDraft({name:'Example',purpose:'A community',preset:'general',language:'en'})})});
  const [accepted,duplicate]=await Promise.all([h.installation.fetch(request()),h.installation.fetch(request())]);expect(accepted.status).toBe(202);expect(duplicate.status).toBe(409);await other.installation.fetch(request());await h.finish();await other.finish();
  expect((h.session() as {job:{worker:string}}).job.worker).not.toBe((other.session() as {job:{worker:string}}).job.worker);
 });
 it('recovers database creation after a lost response without creating duplicates',async()=>{
 const account='a'.repeat(32),job={account,worker:'extb-retry',databaseName:'extb-retry',stage:'database creation',done:['account checks'],draft:makeCommunityDraft({name:'Example',purpose:'Help each other',preset:'general',language:'en'}),release:{version:'v1.2.3',mainModule:'index.js',modules:[],migrations:[],assets:{manifest:{},files:[]}}};
 const h=harness({expires:Date.now()+60000,csrf:'csrf',subject:'owner',encryptedToken:await seal('token',secret),job});let created=false,creates=0;
 vi.stubGlobal('fetch',vi.fn(async(url:string,init?:RequestInit)=>{if(url.endsWith('/d1/database?name=extb-retry'))return Response.json({success:true,result:created?[{uuid:'database-id',name:'extb-retry'}]:[]});if(url.endsWith('/d1/database') && init?.method==='POST'){created=true;creates++;throw Error('lost response');}return Response.json({success:false,errors:[{code:1000}]},{status:503});}));
 const retry=()=>h.installation.fetch(new Request(origin+'/api/retry',{method:'POST',headers:{Origin:origin,'x-csrf-token':'csrf'},body:'{}'}));await retry();await h.finish();await retry();await h.finish();expect(creates).toBe(1);const stored=h.session() as {job:{database:string;done:string[];stage:string}};expect(stored.job.database).toBe('database-id');expect(stored.job.done).toContain('database creation');expect(stored.job.stage).toBe('migrations');
 });
});
