// Browser smoke test against an empty local installation. Never point this at a live community.
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const origin = process.env.EXTB_SMOKE_ORIGIN || 'http://localhost:8787';
if (!['localhost', '127.0.0.1'].includes(new URL(origin).hostname)) throw new Error('Smoke test requires localhost');
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, headless: true });
const owner = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await owner.newPage();
const failures = [];
page.on('pageerror', error => failures.push(error.message));
try {
  await page.goto(origin + '/setup');
  await page.locator('[name=passphrase]').fill(process.env.EXTB_SETUP_PASSPHRASE || 'extb-local-verification-passphrase');
  await page.locator('[name=username]').fill('community_owner');
  await page.locator('[name=password]').fill('Local-Smoke-Owner-42!');
  await page.locator('[name=community_name]').fill('The Workshop');
  await page.getByRole('button', {name: 'Create community'}).click();
  await page.waitForURL(url => url.pathname !== '/setup');
  assert(!await page.locator('body').innerText().then(t => t.includes('Internal Server Error')));
  await page.goto(origin + '/admin/invitations');
  await page.getByRole('button', {name: 'Create invitation'}).click();
  const invitation = await page.locator('input[readonly]').inputValue();
  const member = await browser.newContext();
  const memberPage = await member.newPage();
  await memberPage.goto(invitation);
  await memberPage.locator('[name=display_name]').fill('alex');
  await memberPage.locator('[name=password]').fill('Local-Smoke-Member-42!');
  await memberPage.locator('#tos-pill').click();
  await memberPage.locator('#tos-accept').click();
  await memberPage.getByRole('button', {name:'Create Account'}).click();
  await memberPage.waitForURL(url => url.pathname === '/');
  await memberPage.goto(origin + '/r/general');
  const topicResult = await memberPage.evaluate(async () => {
    const csrf = document.querySelector('[name=csrf]')?.value;
    const response = await fetch('/topics', {method:'POST', body:new URLSearchParams({csrf,room_id:'1',title:'A little corner of the internet, all ours',content:'Welcome to The Workshop. Share what you are building, ask questions, and meet people who care about the same things.'})});
    return {status:response.status,url:response.url,text:await response.text()};
  });
  assert.equal(topicResult.status,200,topicResult.text.slice(0,300));
  assert.match(topicResult.url,/\/t\//);
  await page.goto(origin + '/');
  assert.match(await page.locator('body').innerText(), /A little corner/);
  await mkdir('docs/screenshots', {recursive:true});
  await page.screenshot({path:'docs/screenshots/community.png',fullPage:false});
  await page.goto(origin + '/admin/tokens');
  await page.locator('[name=name]').fill('Smoke test');
  await page.getByRole('button',{name:'Create token'}).click();
  const token = await page.locator('[role=status] code').innerText();
  const rpc = (method,params,id) => owner.request.post(origin+'/mcp',{headers:{Authorization:'Bearer '+token,Accept:'application/json, text/event-stream'},data:{jsonrpc:'2.0',id,method,params}});
  const initialized = await rpc('initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'smoke',version:'1'}},1);
  assert.equal(initialized.status(),200,await initialized.text());
  const tools = await rpc('tools/list',{},2);
  assert.equal(tools.status(),200);
  assert.match(await tools.text(),/community_stats/);
  const unauthorized = await owner.request.post(origin+'/mcp',{data:{jsonrpc:'2.0',id:3,method:'tools/list'}});
  assert.equal(unauthorized.status(),401);
  const guest = await browser.newContext();
  const guestPage = await guest.newPage();
  await guestPage.goto(origin+'/');
  assert.match(await guestPage.locator('body').innerText(),/A little corner/);
  assert.equal((await guest.request.get(origin+'/admin',{maxRedirects:0})).status(),302);
  assert.deepEqual(failures,[]);
  console.log('PASS: setup, invitation registration, approved-member topic creation, public reading, admin access boundary, browser scripts, MCP initialization and scoped tool discovery.');
} finally { await browser.close(); }
